runtime: nodejs14

env_variables:
  RWMATKEY: 4ucF9CGSUAmDL0CSmTmE3FHNH5Dfb1DFzi9Zh0gFLgqjny6nkG7lHykeSgrBE2Uqr9JgObkZgy3%2FOFVRWTP%2FgQ%3D%3D
  FOODINFOKEY: cafcd98bc4e3417ca2fd
  MONGO_URI: mongodb+srv://root:1234@kyrmin.jiuin.mongodb.net/mobileContentse?retryWrites=true&w=majority


inbound_services:
  - warmup

instance_class: F2

